<?php

ob_start();

require_once('section_interesting_lambdas_common.php');
$out1 = ob_get_contents();
ob_end_clean();

$lines = array();
$generated_by = '// generated by: '.__FILE__."\r\n";
$lines[] = $generated_by;
$lines[] = 'const o = {';

$f = explode('function', $out1);
array_shift($f);
foreach ($f as $fi){
    $fi = explode('{', $fi);
    $fname = explode('(', $fi[0]);
    if (trim($fname[0])!= ''){
        $fi = $fi[0];
        $fi_orig = $fi;
        $fi = str_replace('(', ': function (', $fi);
        $lines[] = $fi.'{ return '.$fi_orig.'; },';
    }
}
$lines[] = '}';

$lines[] = 'module.exports = o;';

$s = trim($generated_by.$out1."\r\n".implode("\r\n", $lines));

$dest = dirname(__FILE__).'/../borges/lambdas.js';
$dest = str_replace('\\', '/', $dest);
file_put_contents($dest, $s);
